-- seva_mirror 03-locations: 33 row(s) of locations
SET lock_timeout = '10s';
BEGIN;
INSERT INTO public.seva_mirror (tbl, id, doc) VALUES
('locations','73','{"id":73,"kind":"locality","parent_id":72,"name":"Connaught Place","slug":"connaught-place","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Connaught Place, New Delhi, New Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','74','{"id":74,"kind":"pincode","parent_id":73,"name":"110001","slug":"pin-110001","code":null,"pin_code":"110001","latitude":null,"longitude":null,"search_text":"110001, Connaught Place, New Delhi, New Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','75','{"id":75,"kind":"locality","parent_id":72,"name":"Lajpat Nagar","slug":"lajpat-nagar","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Lajpat Nagar, New Delhi, New Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','76','{"id":76,"kind":"pincode","parent_id":75,"name":"110024","slug":"pin-110024","code":null,"pin_code":"110024","latitude":null,"longitude":null,"search_text":"110024, Lajpat Nagar, New Delhi, New Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','77','{"id":77,"kind":"district","parent_id":70,"name":"South West Delhi","slug":"south-west-delhi","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"South West Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','78','{"id":78,"kind":"city","parent_id":77,"name":"Dwarka","slug":"dwarka","code":null,"pin_code":null,"latitude":28.5921,"longitude":77.046,"search_text":"Dwarka, South West Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','79','{"id":79,"kind":"locality","parent_id":78,"name":"Dwarka Sector 6","slug":"dwarka-sector-6","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Dwarka Sector 6, Dwarka, South West Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','80','{"id":80,"kind":"pincode","parent_id":79,"name":"110075","slug":"pin-110075","code":null,"pin_code":"110075","latitude":null,"longitude":null,"search_text":"110075, Dwarka Sector 6, Dwarka, South West Delhi, Delhi, India","is_active":1}'::jsonb),
('locations','81','{"id":81,"kind":"state","parent_id":1,"name":"Uttar Pradesh","slug":"uttar-pradesh","code":"UP","pin_code":null,"latitude":null,"longitude":null,"search_text":"Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','82','{"id":82,"kind":"district","parent_id":81,"name":"Lucknow","slug":"lucknow","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','83','{"id":83,"kind":"city","parent_id":82,"name":"Lucknow","slug":"lucknow","code":null,"pin_code":null,"latitude":26.8467,"longitude":80.9462,"search_text":"Lucknow, Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','84','{"id":84,"kind":"locality","parent_id":83,"name":"Hazratganj","slug":"hazratganj","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Hazratganj, Lucknow, Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','85','{"id":85,"kind":"pincode","parent_id":84,"name":"226001","slug":"pin-226001","code":null,"pin_code":"226001","latitude":null,"longitude":null,"search_text":"226001, Hazratganj, Lucknow, Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','86','{"id":86,"kind":"locality","parent_id":83,"name":"Gomti Nagar","slug":"gomti-nagar","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Gomti Nagar, Lucknow, Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','87','{"id":87,"kind":"pincode","parent_id":86,"name":"226010","slug":"pin-226010","code":null,"pin_code":"226010","latitude":null,"longitude":null,"search_text":"226010, Gomti Nagar, Lucknow, Lucknow, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','88','{"id":88,"kind":"district","parent_id":81,"name":"Gautam Buddha Nagar","slug":"gautam-buddha-nagar","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Gautam Buddha Nagar, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','89','{"id":89,"kind":"city","parent_id":88,"name":"Noida","slug":"noida","code":null,"pin_code":null,"latitude":28.5355,"longitude":77.391,"search_text":"Noida, Gautam Buddha Nagar, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','90','{"id":90,"kind":"locality","parent_id":89,"name":"Sector 18","slug":"sector-18","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Sector 18, Noida, Gautam Buddha Nagar, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','91','{"id":91,"kind":"pincode","parent_id":90,"name":"201301","slug":"pin-201301","code":null,"pin_code":"201301","latitude":null,"longitude":null,"search_text":"201301, Sector 18, Noida, Gautam Buddha Nagar, Uttar Pradesh, India","is_active":1}'::jsonb),
('locations','92','{"id":92,"kind":"state","parent_id":1,"name":"West Bengal","slug":"west-bengal","code":"WB","pin_code":null,"latitude":null,"longitude":null,"search_text":"West Bengal, India","is_active":1}'::jsonb),
('locations','93','{"id":93,"kind":"district","parent_id":92,"name":"Kolkata","slug":"kolkata","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','94','{"id":94,"kind":"city","parent_id":93,"name":"Kolkata","slug":"kolkata","code":null,"pin_code":null,"latitude":22.5726,"longitude":88.3639,"search_text":"Kolkata, Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','95','{"id":95,"kind":"locality","parent_id":94,"name":"Park Street","slug":"park-street","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Park Street, Kolkata, Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','96','{"id":96,"kind":"pincode","parent_id":95,"name":"700016","slug":"pin-700016","code":null,"pin_code":"700016","latitude":null,"longitude":null,"search_text":"700016, Park Street, Kolkata, Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','97','{"id":97,"kind":"locality","parent_id":94,"name":"Salt Lake City","slug":"salt-lake-city","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Salt Lake City, Kolkata, Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','98','{"id":98,"kind":"pincode","parent_id":97,"name":"700064","slug":"pin-700064","code":null,"pin_code":"700064","latitude":null,"longitude":null,"search_text":"700064, Salt Lake City, Kolkata, Kolkata, West Bengal, India","is_active":1}'::jsonb),
('locations','99','{"id":99,"kind":"state","parent_id":1,"name":"Rajasthan","slug":"rajasthan","code":"RJ","pin_code":null,"latitude":null,"longitude":null,"search_text":"Rajasthan, India","is_active":1}'::jsonb),
('locations','100','{"id":100,"kind":"district","parent_id":99,"name":"Jaipur","slug":"jaipur","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Jaipur, Rajasthan, India","is_active":1}'::jsonb),
('locations','101','{"id":101,"kind":"city","parent_id":100,"name":"Jaipur","slug":"jaipur","code":null,"pin_code":null,"latitude":26.9124,"longitude":75.7873,"search_text":"Jaipur, Jaipur, Rajasthan, India","is_active":1}'::jsonb),
('locations','102','{"id":102,"kind":"locality","parent_id":101,"name":"Malviya Nagar","slug":"malviya-nagar","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Malviya Nagar, Jaipur, Jaipur, Rajasthan, India","is_active":1}'::jsonb),
('locations','103','{"id":103,"kind":"pincode","parent_id":102,"name":"302017","slug":"pin-302017","code":null,"pin_code":"302017","latitude":null,"longitude":null,"search_text":"302017, Malviya Nagar, Jaipur, Jaipur, Rajasthan, India","is_active":1}'::jsonb),
('locations','104','{"id":104,"kind":"locality","parent_id":101,"name":"Vaishali Nagar","slug":"vaishali-nagar","code":null,"pin_code":null,"latitude":null,"longitude":null,"search_text":"Vaishali Nagar, Jaipur, Jaipur, Rajasthan, India","is_active":1}'::jsonb),
('locations','105','{"id":105,"kind":"pincode","parent_id":104,"name":"302021","slug":"pin-302021","code":null,"pin_code":"302021","latitude":null,"longitude":null,"search_text":"302021, Vaishali Nagar, Jaipur, Jaipur, Rajasthan, India","is_active":1}'::jsonb)
ON CONFLICT (tbl, id) DO UPDATE SET doc = EXCLUDED.doc, synced_at = now();
COMMIT;
