-- seva_mirror 05-providers: 10 row(s) of providers
SET lock_timeout = '10s';
BEGIN;
INSERT INTO public.seva_mirror (tbl, id, doc) VALUES
('providers','1','{"id":1,"user_id":null,"business_name":"Borah Plumbing Works","slug":"borah-plumbing-works","contact_name":"Nayan Borah","phone":"9000000001","alt_phone":null,"email":null,"category_id":2,"location_id":5,"pin_code":"781001","address_line":null,"about":"Leak repair, bathroom fittings and motor installation across Guwahati. Same-day response for emergencies.","experience_years":12,"is_verified":1,"status":"active","rating_avg":4.7,"rating_count":63}'::jsonb),
('providers','2','{"id":2,"user_id":null,"business_name":"Dispur Electric Care","slug":"dispur-electric-care","contact_name":"Pranab Deka","phone":"9000000002","alt_phone":null,"email":null,"category_id":3,"location_id":7,"pin_code":"781006","address_line":null,"about":"Wiring, fan and inverter work for homes and small offices. ISI-grade materials only.","experience_years":9,"is_verified":1,"status":"active","rating_avg":4.6,"rating_count":41}'::jsonb),
('providers','3','{"id":3,"user_id":null,"business_name":"Namma Pipe Solutions","slug":"namma-pipe-solutions","contact_name":"Ravi Kumar","phone":"9000000003","alt_phone":null,"email":null,"category_id":2,"location_id":45,"pin_code":"560038","address_line":null,"about":"Residential plumbing across east Bengaluru, including CPVC re-piping.","experience_years":7,"is_verified":0,"status":"active","rating_avg":4.3,"rating_count":28}'::jsonb),
('providers','4','{"id":4,"user_id":null,"business_name":"Andheri Electricians Hub","slug":"andheri-electricians-hub","contact_name":"Salim Shaikh","phone":"9000000004","alt_phone":null,"email":null,"category_id":3,"location_id":24,"pin_code":"400069","address_line":null,"about":"24x7 electrical emergency service for Andheri East and MIDC.","experience_years":15,"is_verified":1,"status":"active","rating_avg":4.8,"rating_count":112}'::jsonb),
('providers','5','{"id":5,"user_id":null,"business_name":"Shiksha Home Tutors","slug":"shiksha-home-tutors","contact_name":"Anjali Deshpande","phone":"9000000005","alt_phone":null,"email":null,"category_id":13,"location_id":32,"pin_code":"411038","address_line":null,"about":"Class 8-12 Maths and Science tutors, verified background checks, demo class free.","experience_years":11,"is_verified":1,"status":"active","rating_avg":4.9,"rating_count":87}'::jsonb),
('providers','6','{"id":6,"user_id":null,"business_name":"Chennai Sparkle Services","slug":"chennai-sparkle-services","contact_name":"Karthik Raja","phone":"9000000006","alt_phone":null,"email":null,"category_id":9,"location_id":60,"pin_code":"600017","address_line":null,"about":"Full-home deep cleaning with a four-member trained team.","experience_years":6,"is_verified":0,"status":"active","rating_avg":4.2,"rating_count":19}'::jsonb),
('providers','7','{"id":7,"user_id":null,"business_name":"Cool Care Delhi","slug":"cool-care-delhi","contact_name":"Mohit Verma","phone":"9000000007","alt_phone":null,"email":null,"category_id":6,"location_id":75,"pin_code":"110024","address_line":null,"about":"Split & window AC service, gas top-up and installation across south Delhi.","experience_years":10,"is_verified":1,"status":"active","rating_avg":4.5,"rating_count":74}'::jsonb),
('providers','8','{"id":8,"user_id":null,"business_name":"Salt Lake Auto Garage","slug":"salt-lake-auto-garage","contact_name":"Debashis Ghosh","phone":"9000000008","alt_phone":null,"email":null,"category_id":25,"location_id":97,"pin_code":"700064","address_line":null,"about":"Doorstep car service and breakdown assistance in Salt Lake and New Town.","experience_years":18,"is_verified":1,"status":"active","rating_avg":4.4,"rating_count":56}'::jsonb),
('providers','9','{"id":9,"user_id":null,"business_name":"Vivah Frames Studio","slug":"vivah-frames-studio","contact_name":"Neha Agarwal","phone":"9000000009","alt_phone":null,"email":null,"category_id":21,"location_id":102,"pin_code":"302017","address_line":null,"about":"Candid wedding photography and cinematography across Rajasthan.","experience_years":8,"is_verified":0,"status":"active","rating_avg":4.6,"rating_count":33}'::jsonb),
('providers','10','{"id":10,"user_id":null,"business_name":"Sharma & Associates CA","slug":"sharma-associates-ca","contact_name":"CA Rahul Sharma","phone":"9000000010","alt_phone":null,"email":null,"category_id":33,"location_id":84,"pin_code":"226001","address_line":null,"about":"ITR filing, GST registration and small-business bookkeeping.","experience_years":14,"is_verified":1,"status":"active","rating_avg":4.8,"rating_count":48}'::jsonb)
ON CONFLICT (tbl, id) DO UPDATE SET doc = EXCLUDED.doc, synced_at = now();
COMMIT;
