#!/usr/bin/env node
/**
 * PANIKA JEEVAN SATHI — deploy to Render through the Render API.
 *
 * Creates (or updates) the Free-plan web service, pushes every environment
 * variable the site needs, triggers a deploy, waits for it to go live and then
 * verifies the public URL.
 *
 *   RENDER_API_KEY=rnd_xxx node scripts/deploy-render.mjs \
 *       --branch main \
 *       --cf-account-id ... --cf-d1-database-id ... --cf-d1-api-token ... \
 *       --r2-account-id ... --r2-bucket ... \
 *       --r2-access-key-id ... --r2-secret-access-key ...
 *
 * When --supabase-url + --supabase-key are supplied the service is pinned to
 * durable storage (PJS_STORAGE=supabase, PJS_REQUIRE_REMOTE=1). Run
 * supabase/schema.sql once in the Supabase SQL editor first (creates the
 * users table and friends). Re-deploys never wipe SUPABASE_* values that
 * were set earlier — an accidental wipe would silently downgrade the site
 * to ephemeral sqlite and lose members at the next Render sleep.
 *
 * Values can also come from the environment (SUPABASE_URL,
 * SUPABASE_SERVICE_ROLE_KEY, SUPABASE_STORAGE_BUCKET, CF_ACCOUNT_ID,
 * CF_D1_DATABASE_ID, CF_D1_API_TOKEN, R2_ACCOUNT_ID, R2_BUCKET,
 * R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, ADMIN_EMAIL, ADMIN_PASSWORD).
 * Anything not supplied is generated by Render (`generateValue`) and printed
 * once by the service log.
 *
 * Everything here is deliberately dependency-free (Node 22 global fetch).
 */

import crypto from 'node:crypto';

/* ------------------------------------------------------------------- config */

const args = process.argv.slice(2);
function arg(name, fallback = undefined) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}
const flags = new Set(args.filter((a) => a.startsWith('--')));

const KEY = arg('key', process.env.RENDER_API_KEY || '');
const API = 'https://api.render.com/v1';
const REPO = arg('repo', 'https://github.com/Spanika4321/panika-jeevan-sathi');
const NAME = arg('name', 'panikajeevansathi'); // → https://panikajeevansathi.onrender.com
const BRANCH = arg('branch', 'main');
const REGION = arg('region', 'singapore'); // closest to India
const PLAN = arg('plan', 'free');

if (!KEY) {
  console.error('\n  RENDER_API_KEY is required (Render dashboard → Account Settings → API keys).\n');
  process.exit(2);
}

const SUPABASE_URL_ARG = arg('supabase-url', process.env.SUPABASE_URL || '').trim();
const SUPABASE_KEY_ARG = arg('supabase-key', process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim();
const SUPABASE_BUCKET_ARG =
  arg('supabase-bucket', process.env.SUPABASE_STORAGE_BUCKET || '').trim() || 'uploads';

if (Boolean(SUPABASE_URL_ARG) !== Boolean(SUPABASE_KEY_ARG)) {
  console.error('\n  --supabase-url and --supabase-key must be supplied together.\n');
  process.exit(2);
}
const hasSupabase = Boolean(SUPABASE_URL_ARG && SUPABASE_KEY_ARG);

const provided = {
  NODE_VERSION: arg('node-version', '22.22.3'),
  HOST: '0.0.0.0',
  SITE_URL: arg('site-url', 'https://panikajeevansathi.onrender.com'),
  ADMIN_EMAIL: arg('admin-email', process.env.ADMIN_EMAIL || 'sukulpanika939@gmail.com'),
  // Durable storage: only pinned when credentials are supplied. Without them
  // PJS_STORAGE is left unset here on purpose — for an EXISTING service the
  // merge below keeps whatever the owner already configured, and for a NEW
  // service the app default (auto) applies. Never write PJS_STORAGE=auto over
  // a Supabase configuration: that silently downgrades to ephemeral sqlite.
  ...(hasSupabase
    ? {
        PJS_STORAGE: 'supabase',
        PJS_REQUIRE_REMOTE: '1',
        SUPABASE_URL: SUPABASE_URL_ARG,
        SUPABASE_SERVICE_ROLE_KEY: SUPABASE_KEY_ARG,
        SUPABASE_STORAGE_BUCKET: SUPABASE_BUCKET_ARG
      }
    : {}),
  CF_ACCOUNT_ID: arg('cf-account-id', process.env.CF_ACCOUNT_ID || ''),
  CF_D1_DATABASE_ID: arg('cf-d1-database-id', process.env.CF_D1_DATABASE_ID || ''),
  CF_D1_API_TOKEN: arg('cf-d1-api-token', process.env.CF_D1_API_TOKEN || ''),
  R2_ACCOUNT_ID: arg('r2-account-id', process.env.R2_ACCOUNT_ID || ''),
  R2_BUCKET: arg('r2-bucket', process.env.R2_BUCKET || ''),
  R2_ACCESS_KEY_ID: arg('r2-access-key-id', process.env.R2_ACCESS_KEY_ID || ''),
  R2_SECRET_ACCESS_KEY: arg('r2-secret-access-key', process.env.R2_SECRET_ACCESS_KEY || '')
};

const explicitAdminPassword = arg('admin-password', process.env.ADMIN_PASSWORD || '');
const explicitSessionSecret = arg('session-secret', process.env.SESSION_SECRET || '');

/** Letters and digits guaranteed, so it always passes the password rules. */
function generatedPassword() {
  const body = crypto.randomBytes(9).toString('base64url').replace(/[^A-Za-z0-9]/g, '');
  return `Pjs${body}Aa1`;
}

/* -------------------------------------------------------------- http helper */

async function api(pathname, { method = 'GET', body, expect = [200, 201] } = {}) {
  const res = await fetch(`${API}${pathname}`, {
    method,
    headers: {
      Authorization: `Bearer ${KEY}`,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: body === undefined ? undefined : JSON.stringify(body),
    signal: AbortSignal.timeout(60000)
  });
  const text = await res.text();
  let json = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch (_) {
    json = null;
  }
  if (!expect.includes(res.status)) {
    const message =
      (json && json.message) ||
      (Array.isArray(json) ? JSON.stringify(json) : '') ||
      text.slice(0, 400);
    throw new Error(`${method} ${pathname} → HTTP ${res.status}: ${message}`);
  }
  return json;
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function step(message) {
  console.log(`  ${message}`);
}

/* ------------------------------------------------------------------- steps */

console.log(`\nDeploying ${NAME} from ${REPO}@${BRANCH} (plan: ${PLAN}, region: ${REGION})`);
console.log(
  hasSupabase
    ? `Storage: supabase (${SUPABASE_URL_ARG}, bucket "${SUPABASE_BUCKET_ARG}") — durable\n`
    : 'Storage: not pinned — service keeps its existing storage config (new service: auto/sqlite, EPHEMERAL on Render!)\n'
);

// 1. workspace (owner) id
let ownerId = arg('owner-id', process.env.RENDER_OWNER_ID || '');
if (!ownerId) {
  const owners = await api('/owners?limit=100');
  const list = (Array.isArray(owners) ? owners : owners.owners || []).map((e) => e.owner || e);
  const user = list.find((o) => String(o.type || '').startsWith('usr')) || list[0];
  if (!user) throw new Error('No Render workspace found for this API key.');
  ownerId = user.id;
}
step(`workspace: ${ownerId}`);

// 2. find an existing service with this name
const services = await api(`/services?name=${encodeURIComponent(NAME)}&limit=20&includePreviews=false`);
const existing = (Array.isArray(services) ? services : []).map((e) => e.service || e).find((s) => s && s.name === NAME);

let service;
let serviceId;

if (existing) {
  serviceId = existing.id;
  step(`service already exists: ${serviceId} (${existing.serviceDetails && existing.serviceDetails.url})`);

  // Keep values Render generated for us the first time (SESSION_SECRET,
  // ADMIN_PASSWORD) so members stay logged in and the admin password stands.
  let current = [];
  try {
    const rows = await api(`/services/${serviceId}/env-vars?limit=100`);
    current = (Array.isArray(rows) ? rows : []).map((r) => r.envVar || r).filter((v) => v && v.key);
  } catch (err) {
    console.log(`  (could not read current environment variables: ${err.message})`);
  }
  // SESSION_SECRET / ADMIN_PASSWORD keep the values Render generated on the
  // first deploy (logins + admin password stay valid).
  // SUPABASE_* / PJS_* are preserved too: wiping them would silently
  // downgrade the site to ephemeral sqlite and lose members at the next
  // Render sleep. Explicit --supabase-* inputs below override these.
  const keep = {
    SESSION_SECRET: true,
    ADMIN_PASSWORD: true,
    SUPABASE_URL: true,
    SUPABASE_SERVICE_ROLE_KEY: true,
    SUPABASE_STORAGE_BUCKET: true,
    PJS_STORAGE: true,
    PJS_REQUIRE_REMOTE: true
  };
  const merged = new Map();
  for (const v of current) {
    if (keep[v.key] && v.value) merged.set(v.key, { key: v.key, value: v.value });
  }
  for (const [key, value] of Object.entries(provided)) {
    if (value) merged.set(key, { key, value });
  }
  if (explicitAdminPassword) merged.set('ADMIN_PASSWORD', { key: 'ADMIN_PASSWORD', value: explicitAdminPassword });
  if (explicitSessionSecret) merged.set('SESSION_SECRET', { key: 'SESSION_SECRET', value: explicitSessionSecret });
  if (!merged.has('SESSION_SECRET')) merged.set('SESSION_SECRET', { key: 'SESSION_SECRET', generateValue: true });
  if (!merged.has('ADMIN_PASSWORD')) merged.set('ADMIN_PASSWORD', { key: 'ADMIN_PASSWORD', generateValue: true });

  await api(`/services/${serviceId}`, {
    method: 'PATCH',
    body: {
      branch: BRANCH,
      autoDeploy: 'yes',
      serviceDetails: {
        plan: PLAN,
        region: REGION,
        runtime: 'node',
        healthCheckPath: '/api/health',
        envSpecificDetails: { buildCommand: 'node -v', startCommand: 'node server.js' }
      }
    }
  });
  await api(`/services/${serviceId}/env-vars`, { method: 'PUT', body: [...merged.values()] });
  service = (await api(`/services/${serviceId}`)).service || (await api(`/services/${serviceId}`));
} else {
  const envVars = Object.entries(provided)
    .filter(([, value]) => value)
    .map(([key, value]) => ({ key, value }));
  envVars.push({ key: 'SESSION_SECRET', generateValue: true });
  envVars.push(
    explicitAdminPassword
      ? { key: 'ADMIN_PASSWORD', value: explicitAdminPassword }
      : { key: 'ADMIN_PASSWORD', generateValue: true }
  );

  const created = await api('/services', {
    method: 'POST',
    body: {
      type: 'web_service',
      name: NAME,
      ownerId,
      repo: REPO,
      branch: BRANCH,
      autoDeploy: 'yes',
      envVars,
      serviceDetails: {
        plan: PLAN,
        region: REGION,
        runtime: 'node',
        numInstances: 1,
        healthCheckPath: '/api/health',
        envSpecificDetails: { buildCommand: 'node -v', startCommand: 'node server.js' }
      }
    }
  });
  service = created.service;
  serviceId = service.id;
  step(`service created: ${serviceId}`);
}

const dashboardUrl = service.dashboardUrl || `https://dashboard.render.com/web/${serviceId}`;
step(`dashboard: ${dashboardUrl}`);

// 3. deploy
const deploy = await api(`/services/${serviceId}/deploys`, {
  method: 'POST',
  body: { clearCache: 'clear' }
});
const deployId = deploy.id || deploy.deployId;
step(`deploy started: ${deployId}`);

let status = 'created';
let deployInfo = null;
for (let i = 0; i < 90; i += 1) {
  deployInfo = await api(`/services/${serviceId}/deploys/${deployId}`);
  status = deployInfo.status;
  process.stdout.write(`\r  status: ${status} (${i * 10}s)          `);
  if (['live', 'build_failed', 'upload_failed', 'canceled', 'deactivated'].includes(status)) break;
  await sleep(10000);
}
console.log('');

if (status !== 'live') {
  try {
    const logs = await api(`/services/${serviceId}/deploys/${deployId}/logs?limit=100&direction=backward`);
    const lines = (Array.isArray(logs) ? logs : logs.logs || []).map((l) => l.line || l.message || '');
    console.log('\n  ---- build log ----');
    console.log(lines.slice(-60).map((l) => `  ${l}`).join('\n'));
  } catch (_) {
    /* no logs */
  }
  throw new Error(`Deploy ended with status "${status}". See ${dashboardUrl}`);
}

const url = (service.serviceDetails && service.serviceDetails.url) || (deployInfo && deployInfo.url);
step(`deploy live: ${status}`);

// 4. verify the public site
if (url && !flags.has('--no-verify')) {
  step(`checking ${url} …`);
  for (let i = 0; i < 30; i += 1) {
    try {
      const res = await fetch(`${url}/api/health`, { signal: AbortSignal.timeout(60000) });
      if (res.ok) {
        const body = await res.json();
        const remoteKind = body.remote && body.remote.kind ? body.remote.kind : '';
        console.log('\n  ──────────────────────────────────────────');
        console.log(`  PUBLIC URL : ${url}`);
        console.log(`  Dashboard  : ${dashboardUrl}`);
        console.log(`  Storage    : ${body.storage}${remoteKind ? ` (remote: ${remoteKind})` : ''}`);
        console.log(`  Photos     : ${body.photos || 'local'}`);
        console.log(
          `  Durable    : ${
            body.durable === true
              ? 'yes — members survive restarts, redeploys and free-tier sleep'
              : 'NO — sqlite/json data is lost when the instance sleeps!'
          }`
        );
        console.log(`  Health     : ${JSON.stringify(body.ok)}`);
        console.log('  ──────────────────────────────────────────\n');
        if (body.durable !== true) {
          console.log(
            '  ⚠  Not durable yet. Run supabase/schema.sql in the Supabase SQL editor,\n' +
              '     then re-run this script with --supabase-url + --supabase-key.\n'
          );
        }
        process.exit(0);
      }
    } catch (_) {
      /* retry */
    }
    await sleep(5000);
  }
  console.log(`\n  Deployed but ${url} did not answer yet — check ${dashboardUrl}\n`);
}

console.log(`\n  PUBLIC URL : ${url || '(see dashboard)'}`);
console.log(`  Dashboard  : ${dashboardUrl}\n`);
