#!/usr/bin/env node
/**
 * PANIKA JEEVAN SATHI — deploy to Render through the Render API.
 *
 * Creates (or updates) the Free-plan web service, pushes every environment
 * variable the site needs, triggers a deploy, waits for it to go live and then
 * verifies the public URL.
 *
 *   RENDER_API_KEY=rnd_xxx node scripts/deploy-render.mjs \
 *       --branch main \
 *       --cf-account-id ... --cf-d1-database-id ... --cf-d1-api-token ...
 *
 * Values can also come from the environment. The three CF_* values are
 * required for durable members + compressed photos; R2_* is optional. Anything not supplied is
 * generated by Render (`generateValue`) and printed once by the service log.
 *
 * Everything here is deliberately dependency-free (Node 22 global fetch).
 */

import crypto from 'node:crypto';

/* ------------------------------------------------------------------- config */

const args = process.argv.slice(2);
function arg(name, fallback = undefined) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}
const flags = new Set(args.filter((a) => a.startsWith('--')));

const KEY = arg('key', process.env.RENDER_API_KEY || '');
const API = 'https://api.render.com/v1';
const REPO = arg('repo', 'https://github.com/Spanika4321/panika-jeevan-sathi');
const NAME = arg('name', 'panikajeevansathi'); // → https://panikajeevansathi.onrender.com
const BRANCH = arg('branch', 'main');
const REGION = arg('region', 'singapore'); // closest to India
const PLAN = arg('plan', 'free');

if (!KEY) {
  console.error('\n  RENDER_API_KEY is required (Render dashboard → Account Settings → API keys).\n');
  process.exit(2);
}

const provided = {
  NODE_VERSION: arg('node-version', '22.22.3'),
  HOST: '0.0.0.0',
  PJS_STORAGE: 'auto',
  SITE_URL: arg('site-url', 'https://panikajeevansathi.onrender.com'),
  ADMIN_EMAIL: arg('admin-email', process.env.ADMIN_EMAIL || 'sukulpanika939@gmail.com'),
  CF_ACCOUNT_ID: arg('cf-account-id', process.env.CF_ACCOUNT_ID || ''),
  CF_D1_DATABASE_ID: arg('cf-d1-database-id', process.env.CF_D1_DATABASE_ID || ''),
  CF_D1_API_TOKEN: arg('cf-d1-api-token', process.env.CF_D1_API_TOKEN || ''),
  R2_ACCOUNT_ID: arg('r2-account-id', process.env.R2_ACCOUNT_ID || ''),
  R2_BUCKET: arg('r2-bucket', process.env.R2_BUCKET || ''),
  R2_ACCESS_KEY_ID: arg('r2-access-key-id', process.env.R2_ACCESS_KEY_ID || ''),
  R2_SECRET_ACCESS_KEY: arg('r2-secret-access-key', process.env.R2_SECRET_ACCESS_KEY || '')
};

const explicitAdminPassword = arg('admin-password', process.env.ADMIN_PASSWORD || '');
const explicitSessionSecret = arg('session-secret', process.env.SESSION_SECRET || '');

const missingD1 = ['CF_ACCOUNT_ID', 'CF_D1_DATABASE_ID', 'CF_D1_API_TOKEN'].filter(
  (key) => !provided[key]
);
if (missingD1.length && !flags.has('--allow-ephemeral')) {
  console.error(`\n  Refusing an unsafe Render deploy: missing ${missingD1.join(', ')}.`);
  console.error('  R2 is optional, but D1 is required to keep members and photos.');
  console.error('  Use --allow-ephemeral only for a disposable demo.\n');
  process.exit(2);
}

/** Letters and digits guaranteed, so it always passes the password rules. */
function generatedPassword() {
  const body = crypto.randomBytes(9).toString('base64url').replace(/[^A-Za-z0-9]/g, '');
  return `Pjs${body}Aa1`;
}

/* -------------------------------------------------------------- http helper */

async function api(pathname, { method = 'GET', body, expect = [200, 201] } = {}) {
  const res = await fetch(`${API}${pathname}`, {
    method,
    headers: {
      Authorization: `Bearer ${KEY}`,
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    body: body === undefined ? undefined : JSON.stringify(body),
    signal: AbortSignal.timeout(60000)
  });
  const text = await res.text();
  let json = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch (_) {
    json = null;
  }
  if (!expect.includes(res.status)) {
    const message =
      (json && json.message) ||
      (Array.isArray(json) ? JSON.stringify(json) : '') ||
      text.slice(0, 400);
    throw new Error(`${method} ${pathname} → HTTP ${res.status}: ${message}`);
  }
  return json;
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function step(message) {
  console.log(`  ${message}`);
}

/* ------------------------------------------------------------------- steps */

console.log(`\nDeploying ${NAME} from ${REPO}@${BRANCH} (plan: ${PLAN}, region: ${REGION})\n`);

// 1. workspace (owner) id
let ownerId = arg('owner-id', process.env.RENDER_OWNER_ID || '');
if (!ownerId) {
  const owners = await api('/owners?limit=100');
  const list = (Array.isArray(owners) ? owners : owners.owners || []).map((e) => e.owner || e);
  const user = list.find((o) => String(o.type || '').startsWith('usr')) || list[0];
  if (!user) throw new Error('No Render workspace found for this API key.');
  ownerId = user.id;
}
step(`workspace: ${ownerId}`);

// 2. find an existing service with this name
const services = await api(`/services?name=${encodeURIComponent(NAME)}&limit=20&includePreviews=false`);
const existing = (Array.isArray(services) ? services : []).map((e) => e.service || e).find((s) => s && s.name === NAME);

let service;
let serviceId;

if (existing) {
  serviceId = existing.id;
  step(`service already exists: ${serviceId} (${existing.serviceDetails && existing.serviceDetails.url})`);

  // Keep values Render generated for us the first time (SESSION_SECRET,
  // ADMIN_PASSWORD) so members stay logged in and the admin password stands.
  let current = [];
  try {
    const rows = await api(`/services/${serviceId}/env-vars?limit=100`);
    current = (Array.isArray(rows) ? rows : []).map((r) => r.envVar || r).filter((v) => v && v.key);
  } catch (err) {
    console.log(`  (could not read current environment variables: ${err.message})`);
  }
  const keep = { SESSION_SECRET: true, ADMIN_PASSWORD: true };
  const merged = new Map();
  for (const v of current) {
    if (keep[v.key] && v.value) merged.set(v.key, { key: v.key, value: v.value });
  }
  for (const [key, value] of Object.entries(provided)) {
    if (value) merged.set(key, { key, value });
  }
  if (explicitAdminPassword) merged.set('ADMIN_PASSWORD', { key: 'ADMIN_PASSWORD', value: explicitAdminPassword });
  if (explicitSessionSecret) merged.set('SESSION_SECRET', { key: 'SESSION_SECRET', value: explicitSessionSecret });
  if (!merged.has('SESSION_SECRET')) merged.set('SESSION_SECRET', { key: 'SESSION_SECRET', generateValue: true });
  if (!merged.has('ADMIN_PASSWORD')) merged.set('ADMIN_PASSWORD', { key: 'ADMIN_PASSWORD', generateValue: true });

  await api(`/services/${serviceId}`, {
    method: 'PATCH',
    body: {
      branch: BRANCH,
      autoDeploy: 'yes',
      serviceDetails: {
        plan: PLAN,
        region: REGION,
        runtime: 'node',
        healthCheckPath: '/api/health',
        envSpecificDetails: { buildCommand: 'node -v', startCommand: 'node server.js' }
      }
    }
  });
  await api(`/services/${serviceId}/env-vars`, { method: 'PUT', body: [...merged.values()] });
  service = (await api(`/services/${serviceId}`)).service || (await api(`/services/${serviceId}`));
} else {
  const envVars = Object.entries(provided)
    .filter(([, value]) => value)
    .map(([key, value]) => ({ key, value }));
  envVars.push({ key: 'SESSION_SECRET', generateValue: true });
  envVars.push(
    explicitAdminPassword
      ? { key: 'ADMIN_PASSWORD', value: explicitAdminPassword }
      : { key: 'ADMIN_PASSWORD', generateValue: true }
  );

  const created = await api('/services', {
    method: 'POST',
    body: {
      type: 'web_service',
      name: NAME,
      ownerId,
      repo: REPO,
      branch: BRANCH,
      autoDeploy: 'yes',
      envVars,
      serviceDetails: {
        plan: PLAN,
        region: REGION,
        runtime: 'node',
        numInstances: 1,
        healthCheckPath: '/api/health',
        envSpecificDetails: { buildCommand: 'node -v', startCommand: 'node server.js' }
      }
    }
  });
  service = created.service;
  serviceId = service.id;
  step(`service created: ${serviceId}`);
}

const dashboardUrl = service.dashboardUrl || `https://dashboard.render.com/web/${serviceId}`;
step(`dashboard: ${dashboardUrl}`);

// 3. deploy
const deploy = await api(`/services/${serviceId}/deploys`, {
  method: 'POST',
  body: { clearCache: 'clear' }
});
const deployId = deploy.id || deploy.deployId;
step(`deploy started: ${deployId}`);

let status = 'created';
let deployInfo = null;
for (let i = 0; i < 90; i += 1) {
  deployInfo = await api(`/services/${serviceId}/deploys/${deployId}`);
  status = deployInfo.status;
  process.stdout.write(`\r  status: ${status} (${i * 10}s)          `);
  if (['live', 'build_failed', 'upload_failed', 'canceled', 'deactivated'].includes(status)) break;
  await sleep(10000);
}
console.log('');

if (status !== 'live') {
  try {
    const logs = await api(`/services/${serviceId}/deploys/${deployId}/logs?limit=100&direction=backward`);
    const lines = (Array.isArray(logs) ? logs : logs.logs || []).map((l) => l.line || l.message || '');
    console.log('\n  ---- build log ----');
    console.log(lines.slice(-60).map((l) => `  ${l}`).join('\n'));
  } catch (_) {
    /* no logs */
  }
  throw new Error(`Deploy ended with status "${status}". See ${dashboardUrl}`);
}

const url = (service.serviceDetails && service.serviceDetails.url) || (deployInfo && deployInfo.url);
step(`deploy live: ${status}`);

// 4. verify the public site
if (url && !flags.has('--no-verify')) {
  step(`checking ${url} …`);
  for (let i = 0; i < 30; i += 1) {
    try {
      const res = await fetch(`${url}/api/health`, { signal: AbortSignal.timeout(60000) });
      if (res.ok) {
        const body = await res.json();
        console.log('\n  ──────────────────────────────────────────');
        console.log(`  PUBLIC URL : ${url}`);
        console.log(`  Dashboard  : ${dashboardUrl}`);
        const photoBackend = body.remote && body.remote.photos && body.remote.photos.backend;
        console.log(`  Storage    : ${body.storage}${body.remote ? ` (photos: ${photoBackend || body.photos})` : ''}`);
        console.log(`  Health     : ${JSON.stringify(body.ok)}`);
        console.log('  ──────────────────────────────────────────\n');
        process.exit(0);
      }
    } catch (_) {
      /* retry */
    }
    await sleep(5000);
  }
  console.log(`\n  Deployed but ${url} did not answer yet — check ${dashboardUrl}\n`);
}

console.log(`\n  PUBLIC URL : ${url || '(see dashboard)'}`);
console.log(`  Dashboard  : ${dashboardUrl}\n`);
