-- =====================================================================
-- SEVA MARKET INDIA — durable storage for user-generated data.
--
-- Paste this whole file into the Supabase SQL editor (Project -> SQL
-- Editor -> New query -> Run). Safe to run more than once.
--
-- WHAT LIVES HERE AND WHY
--   seva_users        accounts        — cannot be regenerated
--   seva_leads        enquiries       — cannot be regenerated
--   seva_audit_logs   activity trail  — cannot be regenerated
--
-- The catalog (locations, categories, providers, services) is NOT here:
-- it is deterministic seed data that the app rebuilds at boot, and a
-- read-only copy already exists in public.seva_mirror.
--
-- WHY THE seva_ PREFIX
--   The same Supabase project may already host Panika Jeevan Sathi, which
--   owns public.users and public.audit_logs. Prefixing keeps the two apps
--   from ever colliding.
--
-- SECURITY MODEL
--   RLS is ON and no policy is created, so anon and authenticated can read
--   nothing even if a key leaks. The server uses the service-role key,
--   which bypasses RLS by design. Grants to anon/authenticated are revoked
--   explicitly as a second line of defence.
-- =====================================================================

SET lock_timeout = '10s';
SET statement_timeout = '60s';

BEGIN;

-- ----------------------------------------------------------- accounts
CREATE TABLE IF NOT EXISTS public.seva_users (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email             text        NOT NULL,
  phone             text,
  full_name         text        NOT NULL,
  password_hash     text        NOT NULL,
  role              text        NOT NULL DEFAULT 'customer'
                                CHECK (role IN ('customer','provider','admin')),
  status            text        NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending','active','suspended')),
  email_verified_at timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness: the app lowercases before writing, and this
-- index is what actually guarantees it under a concurrent signup race.
CREATE UNIQUE INDEX IF NOT EXISTS seva_users_email_unique
  ON public.seva_users (lower(email));
CREATE INDEX IF NOT EXISTS seva_users_status_role_idx
  ON public.seva_users (status, role);

-- --------------------------------------------------------- enquiries
-- provider_id / service_id reference the local catalog by id; there is no
-- FK here on purpose, because the catalog lives in SQLite on the app side.
-- Validity is enforced before the insert (models/lead.js assertTarget).
CREATE TABLE IF NOT EXISTS public.seva_leads (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id   bigint,
  provider_id  bigint      NOT NULL,
  name         text        NOT NULL,
  phone        text        NOT NULL,
  email        text,
  pin_code     text,
  message      text,
  status       text        NOT NULL DEFAULT 'new'
                           CHECK (status IN ('new','contacted','closed','spam')),
  ip_hash      text,       -- HMAC of the client IP: throttling without storing addresses
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS seva_leads_provider_idx
  ON public.seva_leads (provider_id, status, created_at DESC);
-- Backs the per-IP abuse throttle (ip_hash + created_at >= now() - 1 hour).
CREATE INDEX IF NOT EXISTS seva_leads_ip_recent_idx
  ON public.seva_leads (ip_hash, created_at DESC);

-- -------------------------------------------------------- audit trail
CREATE TABLE IF NOT EXISTS public.seva_audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor      text        NOT NULL DEFAULT 'system',
  action     text        NOT NULL,
  entity     text,
  entity_id  bigint,
  detail     text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS seva_audit_logs_entity_idx
  ON public.seva_audit_logs (entity, entity_id);

-- ------------------------------------------------------------ lockdown
ALTER TABLE public.seva_users      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seva_leads      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seva_audit_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.seva_users      FROM anon;
REVOKE ALL ON TABLE public.seva_users      FROM authenticated;
REVOKE ALL ON TABLE public.seva_leads      FROM anon;
REVOKE ALL ON TABLE public.seva_leads      FROM authenticated;
REVOKE ALL ON TABLE public.seva_audit_logs FROM anon;
REVOKE ALL ON TABLE public.seva_audit_logs FROM authenticated;

-- PostgREST caches the schema; tell it about the new tables immediately.
NOTIFY pgrst, 'reload schema';

COMMIT;
