-- PANIKA JEEVAN SATHI — initial Postgres schema
-- Applied by the Supabase GitHub integration on merge to main
-- (Dashboard → Integrations → GitHub → Deploy to production).
-- Idempotent: safe if schema.sql was already pasted in the SQL editor.
-- RLS is enabled with no anon policies so the browser cannot read member data.
-- Keep in sync with ../schema.sql (enforced by scripts/supabase-setup-test.mjs).

create table if not exists users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null default '',
  role text not null default 'user',
  status text not null default 'active',
  email_verified integer not null default 0,
  verification_token text,
  reset_token text,
  reset_expires bigint not null default 0,
  token_version integer not null default 1,
  photo text,
  last_login bigint not null default 0,
  created_at bigint not null
);

create table if not exists profiles (
  user_id bigint primary key references users(id) on delete cascade,
  headline text default '',
  phone text default '',
  age integer,
  gender text default '',
  height_cm integer,
  marital_status text default '',
  religion text default '',
  community text default '',
  sub_community text default '',
  mother_tongue text default '',
  city text default '',
  state text default '',
  country text default '',
  education text default '',
  education_detail text default '',
  occupation text default '',
  company text default '',
  annual_income text default '',
  diet text default '',
  smoking text default '',
  drinking text default '',
  about_me text default '',
  family_type text default '',
  family_status text default '',
  father_occupation text default '',
  mother_occupation text default '',
  siblings text default '',
  gotra text default '',
  manglik text default '',
  pref_age_min integer,
  pref_age_max integer,
  pref_gender text default '',
  pref_location text default '',
  pref_education text default '',
  pref_occupation text default '',
  pref_marital_status text default '',
  pref_religion text default '',
  pref_community text default '',
  pref_message text default '',
  visibility text not null default 'members',
  hide_photo integer not null default 0,
  hide_contact integer not null default 0,
  searchable integer not null default 1,
  profile_complete integer not null default 0,
  updated_at bigint not null default 0
);

create table if not exists interests (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null,
  to_user_id bigint not null,
  message text default '',
  status text not null default 'pending',
  created_at bigint not null,
  responded_at bigint not null default 0
);

create table if not exists shortlist (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  target_user_id bigint not null,
  created_at bigint not null
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null,
  receiver_id bigint not null,
  body text not null,
  created_at bigint not null,
  read_at bigint not null default 0
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  type text not null default 'system',
  title text not null default '',
  body text not null default '',
  link text default '',
  is_read integer not null default 0,
  created_at bigint not null
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null,
  target_user_id bigint not null,
  reason text not null default '',
  details text default '',
  status text not null default 'open',
  created_at bigint not null
);

create table if not exists stories (
  id bigint generated by default as identity primary key,
  title text not null default '',
  couple text not null default '',
  location text default '',
  body text default '',
  photo text default '',
  approved integer not null default 0,
  created_at bigint not null
);

create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text default '',
  phone text default '',
  subject text default '',
  message text not null default '',
  handled integer not null default 0,
  created_at bigint not null
);

create table if not exists settings (
  key text primary key,
  value text
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint not null default 0,
  actor_email text not null default '',
  action text not null default '',
  target_type text not null default '',
  target_id bigint not null default 0,
  detail text not null default '',
  created_at bigint not null
);

create index if not exists idx_interests_to on interests(to_user_id);
create index if not exists idx_interests_from on interests(from_user_id);
create index if not exists idx_msg_receiver on messages(receiver_id);
create index if not exists idx_msg_sender on messages(sender_id);
create index if not exists idx_msg_created on messages(created_at);
create index if not exists idx_notif_user on notifications(user_id, is_read);
create index if not exists idx_shortlist_user on shortlist(user_id);
create index if not exists idx_reports_target on reports(target_user_id);
create index if not exists idx_profiles_gender on profiles(gender);

alter table users enable row level security;
alter table profiles enable row level security;
alter table interests enable row level security;
alter table shortlist enable row level security;
alter table messages enable row level security;
alter table notifications enable row level security;
alter table reports enable row level security;
alter table stories enable row level security;
alter table contact_messages enable row level security;
alter table settings enable row level security;
alter table audit_logs enable row level security;
